### ISSUE TITLE
lots of errors when going on home page

### ISSUE THREAD

**Issue by NedacNostrebor** [alecclyde/TheLoop#142]
"Warning: Encountered two children with the same key, `8W1reQ0Sbg89GFKF7Vpy`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."

**Comment by airgo32** [comment]
This happens when saving in VSCode while on the home page (or any other page that involves listing events). I think it has something to do with the useEffect that loads events firing twice. I've ignored it since there shouldn't be any instances of "saving" in the final product. I have a fix in mind, but it would take a bit of time
